Accessibility Review
lucabenaventew/Portfolio pull request #18
Opened 2022-04-04 19:49 UTC by lucabenaventew

# Accessibility Report
- Page titles
- Image text alternatives
- Text headings
- Color contrast
- Resize
- Interaction
- Moving content
- Multimedia
- The basic structure of the page

2022-04-05 23:47 UTC, OLIPLICHE reviewed
Hi @lucabenaventew , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Please make sure, the node_modules folder should be in the .gitignore file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-06 00:53 UTC, OLIPLICHE requested changes
Hi @lucabenaventew , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linter result is green ✔️
- Commit messages are meaningful✔️
- The pull request have a descriptive title telling you what changes are inside ✔️
- The pull request have a short summary describing introduced changes in more detail ✔️
- node_modules folder is in the .gitignore ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**You can also consider**:

- [ ] You did well in adding  "alt = ..." in the images (`<img alt="alt text ">`). I suggest that you do the same for the image below because this image is important for understanding the content.


![im1](https://user-images.githubusercontent.com/63972670/161874074-348112a6-c1bc-474d-8609-d05fce21829b.JPG)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 00:53 UTC, OLIPLICHE commented on index.html
>  <body>
- [ ] Please make sure that in the "Form section" (Form fields ), Every form control has a `label` associated with it using `label`, `for`, and `id`.

2022-04-06 01:04 UTC, lucabenaventew commented
Hey @OLIPLICHE thank you for your review, I just wonder why you didnt told me this from the beggining, now I just have 1 attempt to send it, It has no sense for me.

2022-04-06 03:05 UTC, OLIPLICHE commented
> Hey @OLIPLICHE thank you for your review, I just wonder why you didnt told me this from the beggining, now I just have 1 attempt to send it, It has no sense for me.

Hi @lucabenaventew, Thank you for reaching out. Please remember to use the same pull request as in your initial review. I reviewed your PR from the start because I did not meet any previous comments from the first review. I provide the link for you to learn more on [How to ask for code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/how_to_ask_for_a_code_review.md)

- [ ] PLEASE CONSIDER MY REQUIRED CHANGE AS OPTIONAL SINCE YOU HAVE ONLY ONE CHANCE LEFT. you can submit the same PR 👍

2022-04-06 03:21 UTC, nicupop729 approved these changes
<h1>Status: Approved 🥇 ✔</h1>
Hi @lucabenaventew,


**I strongly emphasize the importance of implementing the recommendations of the previous reviewer!**
**Please take the time needed to give a meaningful description of the alt attribute of the project image, as well as give labels to the inputs of your form!**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 03:25 UTC, merged