Milestone 1:
lucabenaventew/Portfolio pull request #5
Opened 2022-03-17 22:18 UTC by lucabenaventew

I merged all the branches into features branch

2022-03-18 00:15 UTC, lucabenaventew commented
Hey @chaw-bot, than for your comment, I dont really understand what I have to do, do I have to close this pull request and open another with new title and comment?

2022-03-18 15:10 UTC, BenMukebo requested changes
### Hi **@lucabenaventew,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Good commit messages ✔️ 

 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 15:10 UTC, BenMukebo commented on index.html
> +    </nav>
- [ ] Please remove the logo from your nav tag, the nav tag should contain only nav items
- [ ] Wrap the nav tag in a `header` tag please since this will represent your header section.
- [ ] Consider making your logo a link, it will be used to take the user back to the home page

2022-03-18 15:10 UTC, BenMukebo commented on index.html
> +    </div>
- [ ] Following HTML best practices, it is always good to use semantic tag instead of simple div, by saying that, please change this div into section tag instead.

2022-03-18 15:10 UTC, BenMukebo commented on styles.css
> +
- [ ] Please consider using the same `color, padding, margin, font size`, and all the rest as per the original design, take a look at this below compared to your design 
- [ YOUR DESIGN]

<img width="310" alt="luca" src="https://user-images.githubusercontent.com/79058364/159028307-15c7caec-149a-4360-b248-e3d8e0ec831e.png">
 

- [ ] Do all necessary changes to match this design below ⬇️ 

- [ FIGMA]
<img width="256" alt="BAK" src="https://user-images.githubusercontent.com/79058364/159028568-4c195e98-3576-45f3-8176-667cf86919dc.png">

2022-03-18 19:44 UTC, vic778 requested changes
### STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @lucabenaventew 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Descriptive commits and correct use of the Git Flow :fire:
- [x] :white_check_mark: page titles :white_check_mark: text headings :white_check_mark: resize :white_check_mark: basic structure of the page 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 19:44 UTC, vic778 commented on styles.css
> +}
kindly consider using the same color as was requested by the previous reviewer, (padding, margin, font size), and all the rest as per the original design, take a look at this [Figma template](https://user-images.githubusercontent.com/79058364/159028568-4c195e98-3576-45f3-8176-667cf86919dc.png)

2022-03-18 19:44 UTC, vic778 commented on index.html
> +    <title>Document</title>
- [OPTIONAL] kindly change the title of your project

2022-03-19 17:55 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Luca, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-19 20:00 UTC, merged