Redesign form section of mobile version
lucabenaventew/Portfolio pull request #8
Opened 2022-03-29 18:53 UTC by lucabenaventew

We implemented the full name input for mobile version

2022-03-29 21:54 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @lucabenaventew, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Linters passing
✔️ Good job working so far

## Required 
- [ ] Kindly update your readme with a good description and make sure you add the collaborator info.
- [ ] Kindly add a descriptive PR description.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-29 21:54 UTC, sja-thedude commented on index.html
> +                    name="user_last_name" required maxlength="60" />
- [ ] Kindly follow the figma design and add the social media icons below the contact form.
- [ ] Kindly make sure to align the text area with the name and email address by increasing its width.
- Your design:
<img width="407" alt="Screenshot 2022-03-30 at 12 43 14 AM" src="https://user-images.githubusercontent.com/70269507/160712555-0ec002e5-fff5-4116-a4fa-5a4d8f7165ed.png">

- Figma design:
<img width="251" alt="Screenshot 2022-03-30 at 12 43 01 AM" src="https://user-images.githubusercontent.com/70269507/160712589-4e0c9aac-7841-4ec3-81d1-5830059c91dc.png">

2022-03-29 21:54 UTC, sja-thedude commented on styles.css
- [ ] Kindly use flexbox to layout the elements for the contact form.

2022-03-30 03:12 UTC, lucabenaventew commented
Thank You @sja-thedude for your review, all requirements have been completed.

2022-03-30 03:51 UTC, roshan-bajgain commented
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight:
- 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error at present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Optional suggestions:
-
- [ ]  [OPTIONAL] It would be better if you can add a live demo link for your project in your readme file.  

_I am going to approve your project but hope so you will add the live demo link._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-03-30 04:00 UTC, merged